x-app: &default-app
  build:
    context: "."
    dockerfile: Dockerfile.django
  volumes:
    - .:/app
  env_file:
    - ./src/.env.dev
  depends_on:
    - db
    - node
  restart: "unless-stopped"

services:
  web:
    <<: *default-app 
    container_name: django_web
    image: django_web_image
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  tailwind:
    <<: *default-app
    container_name: django_tailwind
    image: django_tailwind_image
    command: "python manage.py tailwind start"
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true
  db:
    env_file:
      - ./src/.env.dev
    image: postgres:16.2-alpine
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
  node:
    build: 
      context: .
      dockerfile: Dockerfile.node
    image: django_node_image
    container_name: django_node
    volumes:
      - ./src/:/app/

volumes:
  postgres_data:
