services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.web
    container_name: django_web
    image: django_web_image
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/code/
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env.dev
    depends_on:
      - db
      - node
  db:
    env_file:
      - ./src/.env.dev
    image: postgres:16.2-alpine
    container_name: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}
  node:
    build: 
      context: .
      dockerfile: Dockerfile.node
    image: django_node_image
    container_name: django_node
    volumes:
      - ./src/:/code/

volumes:
  postgres_data:
