services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code/
    ports:
      - "8000:8000"
    env_file:
      - ./src/.env.dev
    depends_on:
      - db
  db:
    env_file:
      - ./src/.env.dev
    image: postgres:16.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
      - POSTGRES_DB:${POSTGRES_DB}

volumes:
  postgres_data:
